name: Deploy Static Files to Shared Hosting

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, openssl, tokenizer, json, curl, zip
        tools: composer:v2
        
    - name: Install Node.js dependencies
      run: npm ci
      
    - name: Build frontend assets
      run: npm run build
      
    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader
      
    - name: Create deployment package
      run: |
        DEPLOY_DIR="deploy-$(date +%Y%m%d-%H%M%S)"
        mkdir -p "$DEPLOY_DIR"
        
        # Copy production files
        cp -r public "$DEPLOY_DIR/"
        cp -r src "$DEPLOY_DIR/"
        cp -r database "$DEPLOY_DIR/"
        cp composer.json "$DEPLOY_DIR/"
        cp package.json "$DEPLOY_DIR/"
        cp README.md "$DEPLOY_DIR/"
        cp env.example "$DEPLOY_DIR/"
        
        # Remove development files
        rm -rf "$DEPLOY_DIR/public/assets/dist/node_modules" || true
        rm -rf "$DEPLOY_DIR/public/assets/dist/.git" || true
        
        # Create deployment archive
        tar -czf "${DEPLOY_DIR}.tar.gz" "$DEPLOY_DIR"
        echo "DEPLOY_PACKAGE=${DEPLOY_DIR}.tar.gz" >> $GITHUB_ENV
        
    - name: Upload deployment package
      uses: actions/upload-artifact@v4
      with:
        name: deployment-package
        path: ${{ env.DEPLOY_PACKAGE }}
        
    - name: Deploy to shared hosting
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        script: |
          # Configuration
          REMOTE_PATH="${{ secrets.REMOTE_PATH || '/public_html/delivery-game' }}"
          BACKUP_PATH="${{ secrets.BACKUP_PATH || '/public_html/backups' }}"
          
          # Create backup of current deployment
          echo "Creating backup..."
          mkdir -p $BACKUP_PATH
          if [ -d $REMOTE_PATH ]; then
            tar -czf $BACKUP_PATH/delivery-game-backup-$(date +%Y%m%d-%H%M%S).tar.gz -C $REMOTE_PATH .
          fi
          
          # Remove old deployment
          rm -rf $REMOTE_PATH
          
          # Create new deployment directory
          mkdir -p $REMOTE_PATH
          
          # Extract new deployment
          tar -xzf /tmp/${{ env.DEPLOY_PACKAGE }} -C /tmp/
          cp -r /tmp/deploy-*/* $REMOTE_PATH/
          
          # Set up environment file from secrets
          cd $REMOTE_PATH
          cat > .env << 'EOF'
          DB_HOST=${{ secrets.DB_HOST }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASS=${{ secrets.DB_PASS }}
          APP_ENV=production
          APP_DEBUG=false
          EOF
          
          # Install PHP dependencies
          composer install --no-dev --optimize-autoloader
          
          # Set permissions (no sudo needed for shared hosting)
          chmod -R 755 $REMOTE_PATH
          chmod -R 775 $REMOTE_PATH/database
          
          # Clean up
          rm /tmp/${{ env.DEPLOY_PACKAGE }} || true
          rm -rf /tmp/deploy-* || true
          
          echo "Deployment completed successfully!"
          
    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment completed successfully!"
          echo "Your game is now available at: http://${{ secrets.REMOTE_URL }}/delivery-game"
        else
          echo "❌ Deployment failed!"
        fi 